#! /bin/bash
# Living on the edge!

CLIENT_DIR="rabbitmq-erlang-client"
SERVER_DIR="rabbitmq-server"
CODEGEN_DIR="rabbitmq-codegen"
RABBIT_VERSION="rabbitmq_v2_8_2"

function get_deps {
	cd contrib
	echo "==> $1 (get-deps)"
	git clone "https://github.com/rabbitmq/$1.git"
    cd $1
    git checkout $RABBIT_VERSION
	cd ..
}

function update_deps {
    if [ -d contrib/$1 ]
    then
        cd contrib/$1
        echo "==> $1 (update-deps)"
        git checkout $RABBIT_VERSION
        git pull
        cd ../..
   else
        echo "==> $1 (g-deps)"
        get_deps $1
   fi
}

function delete_deps {
	echo "==> $1 (delete-deps)"
	rm -rf contrib/$1
}

function pre_compile {
	if [ ! -d ebin ]; then
		mkdir ebin
	fi

	if [ ! -d priv ]; then
		mkdir priv
	fi

	# hack for reltool
	if [ ! -d open_rcc ]; then
		mkdir open_rcc
		ln -sf ../ebin open_rcc/ebin
		ln -sf ../src open_rcc/src
		ln -sf ../include open_rcc/include
		ln -sf ../priv open_rcc/priv
		ln -sf ../deps open_rcc/deps
	fi

	# record what commit/version the rep is at
	COMMIT=""
	if [ -d ".git" ]
	then
		COMMIT=`git log -1 --pretty=format:%H`
	fi
	if [ -e "include/commit_ver.hrl" ] && [ ! $COMMIT ]
	then
		exit 0
	else
		if [ ! COMMIT ]
		then
			COMMIT="undefined"
		else
			COMMIT="\"$COMMIT\""
		fi
	fi
	if [ ! -d include ]; then
		mkdir include
	fi
	echo "%% automatically generated by precompile script.  Editing means this
%% will just be overwritten.

-define(COMMIT, $COMMIT)." > include/commit_ver.hrl
}

if [ ! -d contrib ]
then
	mkdir contrib
fi

case $1 in
	"get")
		get_deps $CODEGEN_DIR
		get_deps $CLIENT_DIR
		get_deps $SERVER_DIR;;
	"update")
		update_deps $CODEGEN_DIR
		update_deps $CLIENT_DIR
		update_deps $SERVER_DIR;;
	"delete")
		update_deps $CODEGEN_DIR
		update_deps $CLIENT_DIR
		update_deps $SERVER_DIR;;
	"pre_compile")
		pre_compile;;
esac
